const EmployeeActionTypes = { 
  ADD_EMPLOYEE: "ADD_EMPLOYEE",
  DELETE_EMPLOYEE: "DELETE_EMPLOYEE",
  UPDATE_EMPLOYEE: "UPDATE_EMPLOYEE", 
  UPDATE_EMPLOYEE_LIST: "UPDATE_EMPLOYEE_LIST", 
};

export default EmployeeActionTypes;
